;; -*- Mode: Emacs-Lisp ; Coding: utf-8 -*-

(require 'anything-startup)

;; (setq anything-idle-delay 0.3)
;; (setq anything-input-idle-delay 0.2)
;; (anything-lisp-complete-symbol-set-timer 150)

(defvar anything-c-source-my-dir
  '((name . "Work dir")
    (candidates . (lambda () (directory-files "~/work")))
    (type . file)))

;; ;; ソースの設定
;; (setq anything-sources
;;       '(anything-c-source-buffers+
;;         anything-c-source-work-dir
;;         ;anything-c-source-colors
;;         anything-c-source-recentf
;;         anything-c-source-man-pages
;;         anything-c-source-emacs-commands
;;         anything-c-source-emacs-functions
;;         anything-c-source-files-in-current-dir
;;         anything-c-source-file-name-history
;;         anything-c-source-bookmarks
;;         anything-c-source-locate
;;         ))

(defun my-anything ()
  "Anything command for you.

It is automatically generated by `anything-migrate-sources'."
  (interactive)
  (anything-other-buffer
    '(anything-c-source-buffers+
      anything-c-source-recentf
      anything-c-source-files-in-current-dir+
      anything-c-source-emacs-commands
      anything-c-source-emacs-functions
      anything-c-source-file-name-history
      anything-c-source-bookmarks
      anything-c-source-locate
      anything-c-source-my-dir
      )
    "*my-anything*"))

(define-key anything-map (kbd "C-p") 'anything-previous-line)
(define-key anything-map (kbd "C-n") 'anything-next-line)
(define-key anything-map (kbd "C-v") 'anything-next-source)
(define-key anything-map (kbd "M-v") 'anything-previous-source)
(define-key global-map (kbd "C-;") 'my-anything)

(setq anything-kill-ring-threshold 0)
(global-set-key "\M-y" 'anything-show-kill-ring)









